package com.company;


public enum TokenType {


    FUNCTION,    VARIABLE, KEYWORD_PUBLIC, KEYWORD_STATIC,KEYWORD_VOID, KEYWORD_MAIN, KEYWORD_SYSTEM,
    KEYWORD_OUT, KEYWORD_PRINT, KEYWORD_PRINTLN, KEYWORD_SCANNER, KEYWORD_NEW, KEYWORD_IMPORT, KEYWORD_IF,
    KEYWORD_FOR, KEYWORD_DO,KEYWORD_WHILE, RETURN, KEYWORD_ELSE, SEMICOLON, COMMA, INTEGER_LITERAL,
    STRING_LITERAL, CHAR_LITERAL, ARROW_SYMBOL, LEFT_ANGULAR_BRACKET,RIGHT_ANGULAR_BRACKET, LEFT_CURLY_BRACKET,
    RIGHT_CURLY_BRACKET, INT_DATATYPE, CHAR_DATATYPE, STRING_DATATYPE, BOOL_DATATYPE, LEFT_SQUARE_BRACKET,
    RIGHT_SQUARE_BRACKET,ASSIGNMENT_OPERATOR, AND_SYMBOL, SYMBOL_LESS_THAN, SYMBOL_MORE_THAN, SYMBOL_EQUAL_TO,
    SYMBOL_NOT_EQUAL_TO, SYMBOL_PLUS, SYMBOL_MINUS, SYMBOL_MULTIPLY, SYMBOL_DIVISION, SYMBOL_PERCENTAGE,
    SYMBOL_POWER, LEFT_ROUND_BRACKET, ARRAY_DATATYPE, ARRAYMETHOD_EQUALS, ARRAYMETHOD_FILL, ARRAYMETHOD_SORT,
    ARRAYMETHOD_TOSTRING, QUOTE, METHOD, KEYWORD, RIGHT_ROUND_BRACKET






}
